# Generated by Django 5.2.5 on 2026-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.PositiveIntegerField()),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('changed', 'Changed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Teacher Allocation',
                'verbose_name_plural': 'Teacher Allocations',
                'ordering': ['semester_no', 'course__name'],
            },
        ),
    ]
