# Generated by Django 4.2 on 2026-07-23 18:45

from django.db import migrations, models
import django.db.models.deletion


def clear_old_department_values(apps, schema_editor):
    Instructor = apps.get_model('instructors', 'Instructor')
    Instructor.objects.update(department=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_department_program_department'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='department_name',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(clear_old_department_values),
        migrations.AlterField(
            model_name='instructor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='core.department'),
        ),
    ]
