# Generated by Django 4.2 on 2026-03-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_employment_type'),
        ('instructors', '0002_initial'),
    ]

    operations = [
    ]
