# Generated by Django 4.2 on 2026-05-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_instructor_address_instructor_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
