# Generated by Django 4.2 on 2026-02-23 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=10)),
                ('is_submitted', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('admin_approved_edit', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-date', '-marked_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEditPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('proposed_status', models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('credits', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('num_semesters', models.PositiveIntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAttendance',
            fields=[
                ('faculty_attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Present', max_length=10)),
                ('marked_by_system', models.BooleanField(default=False)),
                ('marked_by_self', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('admin_approved_edit', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-marked_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyAttendanceEditPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('proposed_status', models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_type', models.CharField(blank=True, default='Mid Exam', max_length=50)),
                ('exam_date', models.DateField(blank=True, default=datetime.date(2025, 9, 25), null=True)),
                ('quiz1_marks', models.FloatField(default=0)),
                ('quiz2_marks', models.FloatField(default=0)),
                ('assignment1_marks', models.FloatField(default=0)),
                ('assignment2_marks', models.FloatField(default=0)),
                ('mid_term_marks', models.FloatField(default=0)),
                ('final_marks', models.FloatField(default=0)),
                ('total_marks', models.FloatField()),
                ('obtained_marks', models.FloatField()),
                ('grade', models.CharField(blank=True, default='F', max_length=2)),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('scholarship_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eligibility', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('semester_code', models.CharField(max_length=10, unique=True)),
                ('program', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademicHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('gpa', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
