# Generated by Django 5.2.5 on 2026-06-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_course_parent_course'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('semester_code', models.CharField(max_length=10, unique=True)),
                ('program_old', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academics_semesters', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('course_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Lab')], default='LECTURE', max_length=10)),
                ('parent_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_courses', to='academics.course')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.semester')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademicHistory',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gpa', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
