# Generated by Django 4.2 on 2026-02-23 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructors', '0001_initial'),
        ('students', '0001_initial'),
        ('academics', '0001_initial'),
        ('coordinators', '0002_initial'),
        ('hods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.course'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='students.student'),
        ),
        migrations.AddField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.department'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='scholarships', to='students.student'),
        ),
        migrations.AddField(
            model_name='result',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.course'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student'),
        ),
        migrations.AddField(
            model_name='facultyattendanceeditpermission',
            name='faculty_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_permissions', to='academics.facultyattendance'),
        ),
        migrations.AddField(
            model_name='facultyattendanceeditpermission',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_edit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyattendanceeditpermission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_faculty_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_attendances', to='coordinators.coordinator'),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_attendances', to='hods.hod'),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_attendances', to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_attendances', to='academics.timetable'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='attendanceeditpermission',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_permissions', to='academics.attendance'),
        ),
        migrations.AddField(
            model_name='attendanceeditpermission',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='attendanceeditpermission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendances', to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.timetable'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('course', 'day', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='studentacademichistory',
            unique_together={('student', 'semester')},
        ),
        migrations.AddConstraint(
            model_name='facultyattendance',
            constraint=models.CheckConstraint(check=models.Q(('instructor__isnull', False), ('coordinator__isnull', False), ('hod__isnull', False), _connector='OR'), name='faculty_attendance_has_faculty_member'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceeditpermission',
            unique_together={('instructor', 'attendance', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'timetable', 'date')},
        ),
    ]
