# Generated by Django 5.2.5 on 2026-06-24 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academics_semesters', to='core.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentacademichistory',
            unique_together={('student', 'semester')},
        ),
    ]
