# Generated by Django 4.2 on 2026-05-16 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.course'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenteligibility',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datesheet_eligibility', to='academics.course'),
        ),
        migrations.AddField(
            model_name='studenteligibility',
            name='datesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_records', to='academics.datesheet'),
        ),
        migrations.AddField(
            model_name='studenteligibility',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenteligibility',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datesheet_eligibility', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='studenteligibility',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datesheet_eligibility', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='students.student'),
        ),
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academics_semesters', to='academic_structure.program'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='scholarships', to='students.student'),
        ),
        migrations.AddField(
            model_name='result',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.course'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student'),
        ),
        migrations.AddField(
            model_name='facultyattendanceeditpermission',
            name='faculty_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_permissions', to='academics.facultyattendance'),
        ),
        migrations.AddField(
            model_name='facultyattendanceeditpermission',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_edit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyattendanceeditpermission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_faculty_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_attendances', to='academics.timetable'),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datesheetnotification',
            name='datesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='academics.datesheet'),
        ),
        migrations.AddField(
            model_name='datesheetnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datesheet_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datesheetitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datesheet_items', to='academics.course'),
        ),
        migrations.AddField(
            model_name='datesheetitem',
            name='datesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academics.datesheet'),
        ),
        migrations.AddField(
            model_name='datesheet',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_datesheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datesheet',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datesheets', to='academic_structure.program'),
        ),
        migrations.AddField(
            model_name='datesheet',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_datesheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datesheet',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datesheets', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='parent_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_courses', to='academics.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='attendanceeditpermission',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_permissions', to='academics.attendance'),
        ),
        migrations.AddField(
            model_name='attendanceeditpermission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceeditpermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_edit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.timetable'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('course', 'day', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='studenteligibility',
            unique_together={('datesheet', 'student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='studentacademichistory',
            unique_together={('student', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='datesheetitem',
            unique_together={('datesheet', 'course', 'exam_date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'timetable', 'date')},
        ),
    ]
