# Generated by Django 4.2 on 2026-03-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Lab')], default='LECTURE', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='parent_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_courses', to='academics.course'),
        ),
    ]
