# Generated by Django 4.2 on 2026-05-20 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lower_case_ids'),
        ('academics', '0003_remove_attendanceeditpermission_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academics_semesters', to='core.program'),
        ),
    ]
