# Generated by Django 4.2 on 2026-06-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_course_parent_course'),
        ('academics', '0004_alter_semester_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.batch'),
        ),
    ]
