# Generated by Django 4.2 on 2026-06-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_course_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='batch',
        ),
    ]
