# Generated by Django 4.2 on 2026-05-20 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lower_case_ids'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumversion',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obe_curriculum_versions', to='core.batch'),
        ),
    ]
