# Generated by Django 4.2 on 2026-05-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_program_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='custom_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='custom_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
