# Generated by Django 4.2 on 2026-05-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lower_case_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
