# Generated by Django 4.2 on 2026-05-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customuser_active_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Lab')], max_length=10),
        ),
    ]
