# Generated by Django 4.2 on 2026-06-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_curriculumversion_unique_together_and_more'),
        ('core', '0013_course_parent_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='curriculum_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_batches', to='curriculum.curriculumversion'),
        ),
    ]
