# Generated by Django 4.2 on 2026-08-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_batch_framework_snapshots'),
        ('core', '0023_remove_course_custom_id'),
    ]

    operations = [
    ]
