# Generated by Django 5.2.5 on 2026-05-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.AddField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('datesheet', 'Date Sheet'), ('timetable', 'Time Table')], default='announcement', max_length=20),
        ),
    ]
