# Generated by Django 5.2.5 on 2026-05-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_options_announcement_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
