# Generated by Django 5.2.5 on 2026-02-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='principal_profiles/'),
        ),
    ]
