# Generated by Django 4.2 on 2026-07-03 12:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_batch_graduation_initiated_and_more'),
        ('obe', '0014_alumnisurveycycle_alumnisurveyquestion_gareport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitSurveyGAScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coverage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('respondent_count', models.IntegerField(default=0)),
                ('total_eligible', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_survey_ga_scores', to='core.batch')),
                ('ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_survey_scores', to='obe.ga')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ga', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='CourseFeedbackGAScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coverage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('respondent_count', models.IntegerField(default=0)),
                ('total_eligible', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf_ga_scores', to='core.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf_ga_scores', to='core.course')),
                ('ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf_scores', to='obe.ga')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('course', 'ga', 'batch')},
            },
        ),
    ]
