# Generated by Django 4.2 on 2026-07-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0015_exitsurveygascore_coursefeedbackgascore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clogamapping',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='clogamapping',
            name='clo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_mappings', to='obe.clo', unique=True),
        ),
    ]
