# Generated by Django 4.2 on 2026-07-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0016_alter_clogamapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clogamapping',
            name='clo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ga_mapping', to='obe.clo'),
        ),
    ]
