# Generated by Django 4.2 on 2026-07-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0018_alumni_feedback_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnisurveyresponse',
            name='current_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumnisurveyresponse',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-Employed / Entrepreneur'), ('HIGHER_STUDIES', 'Higher Studies'), ('UNEMPLOYED', 'Unemployed / Looking for job'), ('HOUSEWIFE', 'Housewife / Homemaker')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alumnisurveyresponse',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumnisurveycycle',
            name='auto_extension_days',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
