# Generated by Django 4.2 on 2026-07-09 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obe', '0021_gareport_breakdown_gareport_course_feedback_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gacqirecord',
            name='hod_action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gacqirecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gacqirecord',
            name='issue_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gacqirecord',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gacqirecord',
            name='saved_by_hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_ga_cqis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gacqirecord',
            name='triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gacqirecord',
            name='status',
            field=models.CharField(choices=[('NOT_TRIGGERED', 'Not Triggered'), ('PENDING_HOD_INPUT', 'Pending HOD Input'), ('SAVED', 'Saved'), ('EXPORTED', 'Exported'), ('PENDING', 'Pending'), ('SENT_BACK', 'Sent Back'), ('FULLY_APPROVED', 'Fully Approved')], default='NOT_TRIGGERED', max_length=30),
        ),
    ]
