# Generated by Django 4.2 on 2026-07-12 07:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_is_late_submitter'),
        ('obe', '0023_gareport_gamastercache_gacqirecord_needs_recalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGAEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ga_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_kpi_achieved', models.BooleanField()),
                ('finalized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_entries', to='obe.ga')),
                ('master_cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_entries', to='obe.gamastercache')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_entries', to='students.student')),
            ],
            options={
                'ordering': ['finalized_at'],
                'unique_together': {('master_cache', 'student', 'ga')},
            },
        ),
    ]
