# Generated by Django 4.2 on 2026-08-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0025_gacqirecord_cumulative_close_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegascore',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentcloscore',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
