# Generated by Codex on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0030_flexible_survey_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnisurveysubmission',
            name='employer_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employersurveyresponse',
            name='employer_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
