# Generated by Codex on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0031_employer_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(
                choices=[
                    ('RATING_SCALE', 'Rating Scale (1-5)'),
                    ('SINGLE_SELECT', 'Custom Single Select'),
                    ('TEXT', 'Open Text Box'),
                ],
                default='RATING_SCALE',
                help_text='Rating Scale (1-5), Custom Single Select, or Open Text Box',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='custom_options',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of option labels for SINGLE_SELECT questions (ordered). Optional overrides default rating options)',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='alumnisurveysubmission',
            name='higher_studies_university',
            field=models.CharField(
                blank=True,
                help_text='University / Institution name where pursuing Higher Studies',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='alumnisurveysubmission',
            name='higher_studies_degree',
            field=models.CharField(
                blank=True,
                help_text='e.g. MS Computer Science, MBA, PhD etc.',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='alumnisurveysubmission',
            name='higher_studies_country',
            field=models.CharField(
                blank=True,
                help_text='Country of Higher Studies Institution (optional)',
                max_length=120,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='alumnisurveyanswer',
            name='score',
            field=models.IntegerField(
                blank=True,
                choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')],
                help_text='1-based option index / numeric score (null for TEXT answers or custom option index beyond 5)',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='alumnisurveyanswer',
            name='selected_option_label',
            field=models.CharField(
                blank=True,
                help_text='The option text as it appeared in the survey at submission time (for custom single select)',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='alumnisurveyanswer',
            name='text_answer',
            field=models.TextField(
                blank=True,
                help_text='User entered text when question_type=TEXT',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='employersurveyanswer',
            name='score',
            field=models.IntegerField(
                blank=True,
                choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')],
                help_text='1-based option index / numeric score (null for TEXT answers or custom option index beyond 5)',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='employersurveyanswer',
            name='selected_option_label',
            field=models.CharField(
                blank=True,
                help_text='The option text as it appeared in the survey at submission time (for custom single select)',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='employersurveyanswer',
            name='text_answer',
            field=models.TextField(
                blank=True,
                help_text='User entered text when question_type=TEXT',
                null=True,
            ),
        ),
    ]
