# Generated by Django 4.2 on 2026-08-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0041_academic_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicConfig',
        ),
    ]
