# Generated by Django 5.2 on 2026-09-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0044_direct_vision_mission_keyword_po_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gacqirecord',
            name='remedial_plan',
        ),
        migrations.RemoveField(
            model_name='gacqiresubmissionhistory',
            name='remedial_plan_snapshot',
        ),
        migrations.RemoveField(
            model_name='peocqirecord',
            name='remedial_plan',
        ),
        migrations.RemoveField(
            model_name='peocqisubmissionhistory',
            name='remedial_plan_snapshot',
        ),
    ]
