# Generated by Django 5.2 on 2026-09-03 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_course_selective_group'),
        ('obe', '0045_remove_gacqirecord_remedial_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.program'),
        ),
        migrations.AddField(
            model_name='vision',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visions', to='core.program'),
        ),
    ]
