# Generated by Django 4.2 on 2026-05-17 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('total_semesters', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.program')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('program', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('session_type', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring')], default='fall', max_length=10)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('current_semester', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('graduated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.program')),
            ],
            options={
                'ordering': ['-start_year'],
                'unique_together': {('program', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.batch'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='coordinators', to='core.program'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('course_type', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], max_length=10)),
                ('credit_hours', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.semester')),
            ],
            options={
                'unique_together': {('program', 'code')},
            },
        ),
    ]
