# Generated by Django 4.2 on 2026-05-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_batch_custom_id_customuser_custom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='custom_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
