# Generated by Django 4.2 on 2026-05-17 11:44

from django.db import migrations


def populate_custom_ids(apps, schema_editor):
    User = apps.get_model('core', 'CustomUser')
    
    # We can't import the helper here easily, so we duplicate the logic
    # or just use a simple sequential counter per role
    roles = ['SAC', 'student', 'instructor', 'tvf', 'hod', 'coordinator', 'alumni']
    prefixes = {
        'SAC': 'SAC',
        'student': 'STU',
        'instructor': 'INS',
        'tvf': 'TVF',
        'hod': 'HOD',
        'coordinator': 'CRD',
        'alumni': 'ALM'
    }
    
    for role in roles:
        users = User.objects.filter(role=role, custom_id__isnull=True) | User.objects.filter(role=role, custom_id='')
        prefix = prefixes.get(role, 'USR')
        
        # Start count from current total to avoid overlaps if possible, 
        # but since we filter by null custom_id, we can just start from 1 
        # and check what exists
        count = 1
        for user in users:
            new_id = f"{prefix}-{count:04d}"
            while User.objects.filter(custom_id=new_id).exists():
                count += 1
                new_id = f"{prefix}-{count:04d}"
            
            user.custom_id = new_id
            user.save()
            count += 1

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customuser_original_batch'),
    ]

    operations = [
        migrations.RunPython(populate_custom_ids),
    ]
