# Generated by Django 4.2 on 2026-05-17 11:55

from django.db import migrations


def lower_case_ids(apps, schema_editor):
    User = apps.get_model('core', 'CustomUser')
    
    # Reset all custom_ids first to avoid unique constraint issues
    import uuid
    for user in User.objects.all():
        user.custom_id = f"TEMP-{uuid.uuid4().hex[:8]}"
        user.save()

    prefixes = {
        'SAC': 'sac',
        'student': 'stu',
        'instructor': 'ins',
        'tvf': 'tvf',
        'hod': 'hod',
        'coordinator': 'cod',
        'alumni': 'alm'
    }
    
    roles = ['SAC', 'student', 'instructor', 'tvf', 'hod', 'coordinator', 'alumni']
    
    for role in roles:
        users = User.objects.filter(role=role).order_by('created_at')
        prefix = prefixes.get(role, 'usr')
        count = 1
        
        for user in users:
            dept_code = None
            
            # Logic to find department code
            if role in ['instructor', 'hod', 'coordinator', 'tvf']:
                # Faculty department
                if hasattr(user, 'instructor_profile') and user.instructor_profile.department:
                    dept_code = user.instructor_profile.department.code
                elif hasattr(user, 'programs') and user.programs.exists():
                    dept_code = user.programs.first().code
            elif role == 'student' and user.batch:
                dept_code = user.batch.program.code
            
            if dept_code:
                new_id = f"{dept_code.lower()}-{prefix}-{count:03d}"
            else:
                new_id = f"{prefix}-{count:03d}"
            
            # Final safety check for uniqueness
            while User.objects.filter(custom_id=new_id).exists():
                count += 1
                if dept_code:
                    new_id = f"{dept_code.lower()}-{prefix}-{count:03d}"
                else:
                    new_id = f"{prefix}-{count:03d}"
            
            user.custom_id = new_id
            user.save()
            count += 1

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reformat_custom_ids'),
    ]

    operations = [
        migrations.RunPython(lower_case_ids),
    ]
