# Generated by Django 4.2 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='exit_survey_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='exit_survey_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='graduation_initiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='graduation_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
