# Generated by Django 4.2 on 2026-07-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_batch_exit_survey_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='graduation_initiated',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='graduation_initiated_at',
        ),
        migrations.AddField(
            model_name='batch',
            name='graduation_status',
            field=models.CharField(choices=[('not_graduating', 'Not Graduating'), ('in_progress', 'In Progress'), ('graduated_partial', 'Graduated Partial'), ('graduated_complete', 'Graduated Complete')], default='not_graduating', max_length=20),
        ),
    ]
