# Generated by Django 4.2 on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_batch_graduation_initiated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='alumni_feedback_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='alumni_feedback_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
