# Generated by Django 4.2 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_batch_alumni_feedback_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='alumni_feedback_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
