# Generated by Django 4.2 on 2026-07-23 18:46

from django.db import migrations


def create_initial_department(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    
    # Create Computer Science Department ONLY
    dept, dept_created = Department.objects.get_or_create(
        code='CS',
        defaults={
            'name': 'Computer Science',
            'description': 'Department of Computer Science',
            'is_active': True,
            'custom_id': 'DEP-CS'
        }
    )
    if dept_created:
        dept.custom_id = 'DEP-CS'
        dept.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_department_program_department'),
    ]

    operations = [
        migrations.RunPython(create_initial_department),
    ]
