# Generated by Django 6.0.7 on 2026-08-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_freeze_promotion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='custom_id',
        ),
    ]
