# Generated by Django 4.2 on 2026-08-22 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_lateral_entry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Program Coordinator responsible for this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='ga_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
