# Generated by Django 4.2 on 2026-08-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_batch_coordinator_batch_ga_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='admission_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='entry_semester',
        ),
    ]
