# Generated by Django 4.2 on 2026-08-29 15:01

from django.db import migrations


def convert_tvf_to_instructor(apps, schema_editor):
    """Convert all tvf role users to instructor role with Visiting Faculty designation."""
    CustomUser = apps.get_model('core', 'CustomUser')
    
    # Update all tvf users to instructor role with designation
    tvf_users = CustomUser.objects.filter(role='tvf')
    count = tvf_users.update(role='instructor', designation='Visiting Faculty')
    print(f"Converted {count} tvf users to instructor role with 'Visiting Faculty' designation")


def revert_instructor_to_tvf(apps, schema_editor):
    """Revert: convert instructor users with Visiting Faculty designation back to tvf role."""
    CustomUser = apps.get_model('core', 'CustomUser')
    
    # Revert users with Visiting Faculty designation back to tvf
    vf_users = CustomUser.objects.filter(role='instructor', designation='Visiting Faculty')
    count = vf_users.update(role='tvf', designation=None)
    print(f"Reverted {count} instructor users with 'Visiting Faculty' designation back to tvf role")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_batch_framework_snapshot_fill_audit'),
    ]

    operations = [
        migrations.RunPython(convert_tvf_to_instructor, revert_instructor_to_tvf),
    ]
