# Generated by Django 4.2 on 2026-08-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_convert_tvf_to_instructor_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SAC', 'SAC'), ('hod', 'HOD'), ('coordinator', 'Coordinator'), ('instructor', 'Instructor'), ('student', 'Student'), ('alumni', 'Alumni')], max_length=20),
        ),
    ]
