# Generated by Django 4.2 on 2026-09-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0001_initial'),
        ('core', '0030_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='elective_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='electives.electivegroup'),
        ),
        migrations.AddField(
            model_name='course',
            name='offering_type',
            field=models.CharField(choices=[('COMPULSORY', 'Compulsory'), ('ELECTIVE', 'Elective'), ('SELECTIVE', 'Selective')], default='COMPULSORY', max_length=15),
        ),
    ]
