# Generated by Django 5.2.5 on 2026-02-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('coordinator', 'Coordinator'), ('admin', 'Admin'), ('hod', 'HOD'), ('super_admin', 'Super Admin'), ('principal', 'Principal')], default='student', max_length=20),
        ),
    ]
