# Generated by Django 4.2 on 2026-03-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_course_type_parent_course'),
        ('register', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='IdentifierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(choices=[('SAC', 'Super Admin'), ('JSC', 'Admin (JSC)'), ('PRINCIPAL', 'Principal'), ('INSTRUCTOR', 'Instructor'), ('HOD', 'HOD'), ('COORDINATOR', 'Coordinator'), ('STUDENT', 'Student')], max_length=20)),
                ('prefix', models.CharField(max_length=20)),
                ('next_sequence', models.IntegerField(default=1)),
                ('padding', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department')),
            ],
            options={
                'ordering': ['role_key'],
                'unique_together': {('role_key', 'department')},
            },
        ),
    ]
