# Generated by Django 4.2 on 2026-05-20 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordinators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherallocation',
            name='curriculum_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='curriculum.curriculumversion'),
        ),
        migrations.AddField(
            model_name='teacherallocation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teacherallocation',
            unique_together={('curriculum_version', 'course', 'batch', 'semester_no')},
        ),
    ]
