# Generated by Django 4.2 on 2026-05-20 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lower_case_ids'),
        ('coordinators', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherallocation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_allocations', to='core.batch'),
        ),
    ]
