# Generated by Django 5.2.5 on 2026-06-24 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('core', '0002_initial'),
        ('obe', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.batch'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
        migrations.AddField(
            model_name='cloattainment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch'),
        ),
        migrations.AddField(
            model_name='cloattainment',
            name='clo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.clo'),
        ),
        migrations.AddField(
            model_name='cloattainment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AddField(
            model_name='cloattainment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
        migrations.AddField(
            model_name='coursethreshold',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AddField(
            model_name='coursethreshold',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
        migrations.AddField(
            model_name='cqi',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.batch'),
        ),
        migrations.AddField(
            model_name='cqi',
            name='clo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.clo'),
        ),
        migrations.AddField(
            model_name='cqi',
            name='clo_attainment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.cloattainment'),
        ),
        migrations.AddField(
            model_name='cqi',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AddField(
            model_name='cqi',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cqi_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cqi',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cqi_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cqi',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='question',
            name='clo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.clo'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentquestionmark',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='studentquestionmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentrubricscore',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.rubric'),
        ),
        migrations.AddField(
            model_name='studentrubricscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='cqi',
            unique_together={('course', 'batch', 'semester', 'clo', 'instructor')},
        ),
        migrations.AlterUniqueTogether(
            name='studentquestionmark',
            unique_together={('student', 'question')},
        ),
    ]
