# Generated by Django 5.2.5 on 2026-06-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cqi',
            old_name='hod_comment',
            new_name='coordinator_comment',
        ),
        migrations.AddField(
            model_name='cqi',
            name='show_next_offering',
            field=models.BooleanField(default=False),
        ),
    ]
