# Generated by Django 4.2 on 2026-07-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_studentquestionmark_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cqi',
            name='hod_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
