# Generated by Django 6.0.7 on 2026-08-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_awaiting_external_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('presentation', 'Presentation'), ('midterm', 'Midterm'), ('final', 'Final')], max_length=20),
        ),
    ]
