# Generated by Django 6.0.7 on 2026-08-14 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_assessment_assessment_type'),
        ('obe', '0035_alter_clo_bloom_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='bloom_level',
            field=models.CharField(blank=True, choices=[('K1', 'Remember'), ('K2', 'Understand'), ('K3', 'Apply'), ('K4', 'Analyze'), ('K5', 'Evaluate'), ('K6', 'Create')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='clo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obe.clo'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
