# Generated by Django 4.2 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exit_survey_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='exit_survey_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('alumni', 'Alumni')], default='active', max_length=20),
        ),
    ]
