# Generated by Django 4.2 on 2026-07-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_exit_survey_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
