# Generated by Django 4.2 on 2026-07-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_is_active_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_late_submitter',
            field=models.BooleanField(default=False),
        ),
    ]
