# Generated by Django 4.2 on 2026-07-23 18:45

from django.db import migrations, models
import django.db.models.deletion


def clear_student_department_values(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student.objects.update(department=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_department_program_department'),
        ('students', '0007_student_is_late_submitter'),
    ]

    operations = [
        migrations.RunPython(clear_student_department_values),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
    ]
