# Generated by Django 4.2 on 2026-07-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_rename_hod_comment_cqi_coordinator_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cqi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
