# Generated by Django 4.2 on 2026-07-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0002_reportinvalidationlog'),
        ('students', '0007_student_is_late_submitter'),
        ('assessments', '0004_cqi_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentquestionmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course_retake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='retake.courseretake'),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='course_retake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='retake.courseretake'),
        ),
        migrations.AddField(
            model_name='studentquestionmark',
            name='course_retake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_question_marks', to='retake.courseretake'),
        ),
        migrations.AlterUniqueTogether(
            name='studentquestionmark',
            unique_together={('student', 'question', 'course_retake')},
        ),
    ]
