# Generated by Django 4.2 on 2026-08-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_lateral_entry_credit_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='entry_semester',
        ),
        migrations.DeleteModel(
            name='CreditTransfer',
        ),
    ]
