# Generated by Django 4.2 on 2026-05-20 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_structure', '0002_semester_course'),
        ('core', '0010_lower_case_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.PositiveIntegerField()),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('changed', 'Changed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations_made', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_allocations', to='academic_structure.batch')),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='coordinators.teacherallocation')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_allocations', to='core.course')),
            ],
            options={
                'verbose_name': 'Teacher Allocation',
                'verbose_name_plural': 'Teacher Allocations',
                'ordering': ['semester_no', 'course__name'],
            },
        ),
    ]
