# Generated by Django 4.2 on 2026-02-23 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
        ('coordinators', '0001_initial'),
        ('hods', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='coordinators.timetableproposal'),
        ),
        migrations.AddField(
            model_name='timetableproposal',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_proposals', to='coordinators.coordinator'),
        ),
        migrations.AddField(
            model_name='timetableproposal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hods.hod'),
        ),
        migrations.AddField(
            model_name='timetableproposal',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hods.hod'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='coordinators.coordinator'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='coordinatordashboard',
            name='coordinator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='coordinators.coordinator'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hods.hod'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department'),
        ),
    ]
