# Generated by Django 4.2 on 2026-02-23 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinators', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('proposal', 'day', 'start_time', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together={('course', 'semester')},
        ),
    ]
