# Generated by Django 4.2 on 2026-06-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0003_alter_teacherallocation_batch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherallocation',
            unique_together=set(),
        ),
    ]
