# Generated by Django 5.2.5 on 2026-03-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='can_act_as_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
