# Generated by Django 5.2.5 on 2026-03-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0004_alter_coordinator_can_act_as_instructor'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='coordinators.courseallocation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
