# Generated by Django 4.2 on 2026-05-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_address_student_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='custom_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
