# Generated by Django 4.2 on 2026-08-31 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0044_direct_vision_mission_keyword_po_mapping'),
        ('retake', '0002_reportinvalidationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseretake',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('passed', 'Passed'), ('failed_again', 'Failed Again'), ('dropped', 'Dropped')], default='ongoing', max_length=20),
        ),
        migrations.CreateModel(
            name='RetakeEvaluationElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255)),
                ('element_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('midterm', 'Midterm'), ('final', 'Final'), ('project', 'Project'), ('presentation', 'Presentation'), ('sessional', 'Student Performance')], max_length=50)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date', models.DateField(blank=True, null=True)),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retake_evaluation_elements', to='obe.clo')),
                ('retake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_elements', to='retake.courseretake')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='retakeevaluationelement',
            index=models.Index(fields=['retake', 'element_type'], name='retake_reta_retake__dac73e_idx'),
        ),
    ]
