# Generated by Django 4.2 on 2026-08-31 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retake', '0003_alter_courseretake_status_retakeevaluationelement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetakeAssessmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_course_id', models.UUIDField()),
                ('original_batch_id', models.UUIDField()),
                ('original_semester_id', models.UUIDField()),
                ('snapshot_data', models.JSONField()),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retake', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_snapshot', to='retake.courseretake')),
            ],
        ),
        migrations.DeleteModel(
            name='RetakeEvaluationElement',
        ),
        migrations.AddIndex(
            model_name='retakeassessmentsnapshot',
            index=models.Index(fields=['retake', 'is_locked'], name='retake_reta_retake__2507da_idx'),
        ),
    ]
