# Generated by Django 4.2 on 2026-02-23 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_initial'),
        ('hods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodregistrationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hodfeedbackcontrol',
            name='hod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_control', to='hods.hod'),
        ),
        migrations.AddField(
            model_name='hod',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department'),
        ),
        migrations.AddField(
            model_name='hod',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
