# Generated by Django 5.2.5 on 2026-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hods', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='retirement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
