# Generated by Django 5.2.5 on 2026-06-28 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('feedback', '0002_alter_feedbackresponse_course_and_more'),
        ('obe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCQI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('INSTRUCTOR', 'Instructor'), ('COORDINATOR', 'Coordinator')], max_length=20)),
                ('root_cause', models.TextField()),
                ('remedial_action', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IMPLEMENTED', 'Implemented')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch')),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.clo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('implemented_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implemented_feedback_cqi', to='core.batch')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
        ),
    ]
