# Generated by Django 4.2 on 2026-07-10 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0007_student_is_late_submitter'),
        ('core', '0018_batch_alumni_feedback_due_at'),
        ('obe', '0022_gacqirecord_hod_action_plan_gacqirecord_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCLOMasterCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_fully_compiled', models.BooleanField(default=False)),
                ('total_courses_expected', models.IntegerField(default=0)),
                ('total_courses_finalized', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clo_master_caches', to='core.batch')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_master_caches', to='core.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_master_caches', to='core.semester')),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('program', 'batch', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CourseCLOMasterEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clo_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_kpi_achieved', models.BooleanField()),
                ('finalized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_master_entries', to='obe.clo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_master_entries', to='core.course')),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_master_entries', to='obe.coursesession')),
                ('master_cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_entries', to='clo_master.semesterclomastercache')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_master_entries', to='students.student')),
            ],
            options={
                'ordering': ['finalized_at'],
                'unique_together': {('master_cache', 'course_session', 'clo', 'student')},
            },
        ),
    ]
