# Generated by Django 4.2 on 2026-05-16 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.timetable'),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records_faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulkattendancesession',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulkattendancesession',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.timetable'),
        ),
        migrations.AddField(
            model_name='attendanceupdaterequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_update_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceupdaterequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_update_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceupdaterequest',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_update_requests', to='academics.timetable'),
        ),
        migrations.AddField(
            model_name='attendanceeditrequest',
            name='faculty_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.facultyattendance'),
        ),
        migrations.AddField(
            model_name='attendanceeditrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceeditrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceeditrequest',
            name='student_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.studentattendance'),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date', 'status'], name='attendance__date_514473_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'date'], name='attendance__student_0335ea_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['course', 'date'], name='attendance__course__9ce8ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'timetable', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='bulkattendancesession',
            unique_together={('instructor', 'timetable', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendanceupdaterequest',
            index=models.Index(fields=['status', 'attendance_date'], name='attendance__status_52179d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceupdaterequest',
            index=models.Index(fields=['requested_by', 'created_at'], name='attendance__request_f81716_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['student', 'is_resolved'], name='attendance__student_deda3d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['course', 'alert_type'], name='attendance__course__7611e6_idx'),
        ),
    ]
