# Generated by Django 4.2 on 2026-02-23 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('attendance', '0002_initial'),
        ('academics', '0002_initial'),
        ('coordinators', '0002_initial'),
        ('hods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.timetable'),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinators.coordinator'),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hods.hod'),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='bulkattendancesession',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='bulkattendancesession',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.timetable'),
        ),
        migrations.AddField(
            model_name='attendanceeditrequest',
            name='faculty_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.facultyattendance'),
        ),
        migrations.AddField(
            model_name='attendanceeditrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceeditrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceeditrequest',
            name='student_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.studentattendance'),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date', 'status'], name='attendance__date_514473_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'date'], name='attendance__student_0335ea_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['course', 'date'], name='attendance__course__9ce8ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'timetable', 'date')},
        ),
        migrations.AddConstraint(
            model_name='facultyattendance',
            constraint=models.CheckConstraint(check=models.Q(('instructor__isnull', False), ('coordinator__isnull', False), ('hod__isnull', False), _connector='OR'), name='faculty_attendance_has_faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='bulkattendancesession',
            unique_together={('instructor', 'timetable', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['student', 'is_resolved'], name='attendance__student_deda3d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['course', 'alert_type'], name='attendance__course__7611e6_idx'),
        ),
    ]
