# Generated by Django 5.2.5 on 2026-03-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendanceupdaterequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendanceupdaterequest',
            new_name='attendance__status_52179d_idx',
            old_name='attendance_a_status_3fef11_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceupdaterequest',
            new_name='attendance__request_f81716_idx',
            old_name='attendance_a_request_e06ec5_idx',
        ),
    ]
