# Generated by Django 4.2 on 2026-05-17 13:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0002_semester_course'),
        ('instructors', '0002_instructor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_number', models.IntegerField()),
                ('kpi_target', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clos', to='academic_structure.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clos', to='academic_structure.course')),
            ],
            options={
                'ordering': ['order_number'],
                'unique_together': {('course', 'batch', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='GA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas', to='academic_structure.program')),
            ],
            options={
                'ordering': ['order_number'],
                'unique_together': {('program', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='PEO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peos', to='academic_structure.program')),
            ],
            options={
                'ordering': ['order_number'],
                'unique_together': {('program', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='GAPEOMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peo_mappings', to='obe.ga')),
                ('peo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_mappings', to='obe.peo')),
            ],
            options={
                'unique_together': {('ga', 'peo')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], max_length=10)),
                ('semester_number', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_versions', to='academic_structure.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_versions', to='academic_structure.course')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('batch', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='academic_structure.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic_structure.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_sessions', to='instructors.instructor')),
            ],
            options={
                'ordering': ['-academic_year'],
                'unique_together': {('course', 'batch', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='CLOGAMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_mappings', to='obe.clo')),
                ('ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_mappings', to='obe.ga')),
            ],
            options={
                'unique_together': {('clo', 'ga')},
            },
        ),
    ]
