# Generated by Django 5.2.5 on 2026-06-24 18:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('curriculum', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_number', models.IntegerField()),
                ('bloom_level', models.CharField(choices=[('K1', 'K1 - Remembering'), ('K2', 'K2 - Understanding'), ('K3', 'K3 - Applying'), ('K4', 'K4 - Analyzing'), ('K5', 'K5 - Evaluating'), ('K6', 'K6 - Creating')], default='K2', max_length=10)),
                ('kpi_target', models.FloatField(default=60.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clos', to='core.course')),
                ('curriculum_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clos', to='curriculum.curriculumversion')),
            ],
            options={
                'ordering': ['order_number'],
                'unique_together': {('course', 'curriculum_version', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_done', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ASSESSMENT_DONE', 'Assessment Done')], default='IN_PROGRESS', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.semester')),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course', 'batch', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='GA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_number', models.IntegerField()),
                ('kpi_threshold', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas', to='core.program')),
            ],
            options={
                'ordering': ['order_number'],
                'unique_together': {('program', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='GACQIRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cqi_level', models.CharField(choices=[('SEMESTER', 'Semester End CQI'), ('CUMULATIVE', 'Program End CQI')], default='SEMESTER', max_length=30)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('attainment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kpi_threshold_at_trigger', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('remedial_plan', models.TextField(blank=True, null=True)),
                ('hod_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT_BACK', 'Sent Back'), ('FULLY_APPROVED', 'Fully Approved')], default='PENDING', max_length=30)),
                ('is_audit_visible', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ga_cqis', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ga_cqi_records', to='core.batch')),
                ('ga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cqi_records', to='obe.ga')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_ga_cqis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GACQIResubmissionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('root_cause_snapshot', models.TextField(blank=True, null=True)),
                ('remedial_plan_snapshot', models.TextField(blank=True, null=True)),
                ('hod_comment_snapshot', models.TextField(blank=True, null=True)),
                ('status_at_time', models.CharField(max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('cqi_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='obe.gacqirecord')),
            ],
        ),
        migrations.CreateModel(
            name='PEO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_number', models.IntegerField()),
                ('kpi_threshold', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peos', to='core.program')),
            ],
            options={
                'ordering': ['order_number'],
                'unique_together': {('program', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='CourseGAScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('enrolled_students', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_scores', to='obe.coursesession')),
                ('ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_scores', to='obe.ga')),
            ],
            options={
                'unique_together': {('course_session', 'ga')},
            },
        ),
        migrations.CreateModel(
            name='CLOGAMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_mappings', to='obe.clo')),
                ('ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_mappings', to='obe.ga')),
            ],
            options={
                'unique_together': {('clo', 'ga')},
            },
        ),
        migrations.CreateModel(
            name='GAPEOMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peo_mappings', to='obe.ga')),
                ('peo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_mappings', to='obe.peo')),
            ],
            options={
                'unique_together': {('ga', 'peo')},
            },
        ),
        migrations.CreateModel(
            name='StudentCLOScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attainment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='obe.clo')),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_clo_scores', to='obe.coursesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_scores', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'clo', 'course_session')},
            },
        ),
    ]
