# Generated by Django 4.2 on 2026-02-23 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_initial'),
        ('obe', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessment',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obe_assessments', to='students.student'),
        ),
        migrations.AddField(
            model_name='obereport',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obe_reports', to='academics.course'),
        ),
        migrations.AddField(
            model_name='obereport',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obe_reports', to='academics.department'),
        ),
        migrations.AddField(
            model_name='obereport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obeconfiguration',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obe_config', to='academics.department'),
        ),
        migrations.AddField(
            model_name='obeconfiguration',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graduateattribute',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_attributes', to='academics.department'),
        ),
        migrations.AddField(
            model_name='gaattainment',
            name='ga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainments', to='obe.graduateattribute'),
        ),
        migrations.AddField(
            model_name='gaattainment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_attainments', to='students.student'),
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='academics.course'),
        ),
        migrations.AddField(
            model_name='cloattainment',
            name='clo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainments', to='obe.courseoutcome'),
        ),
        migrations.AddField(
            model_name='cloattainment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_attainments', to='students.student'),
        ),
        migrations.AddField(
            model_name='clo_ga_mapping',
            name='clo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_mappings', to='obe.courseoutcome'),
        ),
        migrations.AddField(
            model_name='clo_ga_mapping',
            name='ga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_mappings', to='obe.graduateattribute'),
        ),
        migrations.AddField(
            model_name='assessmentclomapping',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_mappings', to='obe.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentclomapping',
            name='clo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_mappings', to='obe.courseoutcome'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentassessment',
            unique_together={('student', 'assessment')},
        ),
        migrations.AlterUniqueTogether(
            name='graduateattribute',
            unique_together={('code', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='gaattainment',
            unique_together={('ga', 'student', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='courseoutcome',
            unique_together={('code', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='cloattainment',
            unique_together={('clo', 'student', 'semester_year')},
        ),
        migrations.AlterUniqueTogether(
            name='clo_ga_mapping',
            unique_together={('clo', 'ga')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentclomapping',
            unique_together={('assessment', 'clo')},
        ),
    ]
