# Generated by Django 5.2.5 on 2026-05-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0002_semester_course'),
        ('obe', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ga',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ga',
            name='code',
            field=models.CharField(default='GA-001', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ga',
            unique_together={('program', 'code')},
        ),
    ]
