# Generated by Django 4.2 on 2026-05-23 08:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ga',
            name='kpi_target',
            field=models.FloatField(default=60.0),
        ),
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('kpi', models.FloatField(default=60.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_indicators', to='obe.ga')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CLOPIMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_mappings', to='obe.clo')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_mappings', to='obe.performanceindicator')),
            ],
            options={
                'unique_together': {('clo', 'pi')},
            },
        ),
    ]
