# Generated by Django 5.2.5 on 2026-03-08 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('obe', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentCLOMapping',
        ),
        migrations.DeleteModel(
            name='CLO_GA_Mapping',
        ),
        migrations.DeleteModel(
            name='CLOAttainment',
        ),
        migrations.DeleteModel(
            name='GAAttainment',
        ),
        migrations.DeleteModel(
            name='StudentAssessment',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='CourseOutcome',
        ),
        migrations.DeleteModel(
            name='OBEConfiguration',
        ),
        migrations.DeleteModel(
            name='OBEReport',
        ),
        migrations.DeleteModel(
            name='GraduateAttribute',
        ),
        migrations.CreateModel(
            name='GraduateAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clo_number', models.IntegerField()),
                ('description', models.TextField()),
                ('bloom_level', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='CLOGAMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.clo')),
                ('ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.graduateattribute')),
            ],
        ),
    ]
