# Generated by Django 4.2 on 2026-06-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_batch_curriculum_version'),
        ('curriculum', '0004_alter_curriculumversion_unique_together_and_more'),
        ('obe', '0002_ga_kpi_target_performanceindicator_clopimapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clo',
            name='curriculum_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clos', to='curriculum.curriculumversion'),
        ),
        migrations.AlterUniqueTogether(
            name='clo',
            unique_together={('course', 'curriculum_version', 'order_number')},
        ),
        migrations.RemoveField(
            model_name='clo',
            name='batch',
        ),
    ]
