# Generated by Django 4.2 on 2026-03-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0003_remove_assessmentclomapping_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clogamapping',
            name='weightage',
            field=models.FloatField(default=1),
        ),
    ]
