# Generated by Django 4.2 on 2026-06-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0003_alter_clo_unique_together_clo_curriculum_version_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurriculumVersion',
        ),
    ]
