# Generated by Django 4.2 on 2026-03-14 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('obe', '0003_remove_assessmentclomapping_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clogamapping',
            name='weightage',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='clo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clos', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='clogamapping',
            name='clo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_mappings', to='obe.clo'),
        ),
    ]
