# Generated by Django 4.2 on 2026-03-14 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('obe', '0004_clogamapping_weightage_alter_clo_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clo',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.department'),
        ),
        migrations.AddField(
            model_name='clo',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
    ]
