# Generated by Django 4.2 on 2026-06-19 07:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0004_delete_curriculumversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGAScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('is_stale', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GACQIRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('SEMESTER_EARLY_WARNING', 'Semester-End Early Warning'), ('PROGRAM_MASTER_CQI', 'Program-Level Master CQI')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('remedy', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING_HOD_APPROVAL', 'Pending HOD Approval'), ('SENT_BACK', 'Sent Back'), ('FULLY_APPROVED', 'Fully Approved')], default='PENDING_HOD_APPROVAL', max_length=30)),
                ('hod_rejection_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GACQIResubmissionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_snapshot', models.TextField()),
                ('remedy_snapshot', models.TextField()),
                ('status_at_time', models.CharField(max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('cqi_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='obe.gacqirecord')),
            ],
        ),
        migrations.RemoveField(
            model_name='ga',
            name='kpi_target',
        ),
        migrations.AddField(
            model_name='coursesession',
            name='assessment_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ASSESSMENT_DONE', 'Assessment Done')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AddField(
            model_name='ga',
            name='kpi_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='clogamapping',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
        migrations.AddField(
            model_name='gacqirecord',
            name='affected_course_sessions',
            field=models.ManyToManyField(related_name='ga_cqi_records', to='obe.coursesession'),
        ),
        migrations.AddField(
            model_name='gacqirecord',
            name='ga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cqi_records', to='obe.ga'),
        ),
        migrations.AddField(
            model_name='coursegascore',
            name='course_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_scores', to='obe.coursesession'),
        ),
        migrations.AddField(
            model_name='coursegascore',
            name='ga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_scores', to='obe.ga'),
        ),
        migrations.AlterUniqueTogether(
            name='coursegascore',
            unique_together={('course_session', 'ga')},
        ),
    ]
