# Generated by Django 4.2 on 2026-03-15 09:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('academics', '0002_initial'),
        ('obe', '0004_clogamapping_weightage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('midterm', 'Mid-term Exam'), ('final', 'Final Exam'), ('project', 'Project'), ('presentation', 'Presentation'), ('lab', 'Lab Work')], max_length=20)),
                ('total_marks', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weightage', models.FloatField(default=1, help_text='Weightage in percentage (0-100).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('assessment_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obe_assessments', to='academics.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_obe_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessment_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='obe.assessment')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_obe_assessments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obe_assessments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentCLOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.FloatField(default=1, help_text='Weightage in percentage (0-100).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_mappings', to='obe.assessment')),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_mappings', to='obe.clo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentassessment',
            constraint=models.UniqueConstraint(fields=('student', 'assessment'), name='unique_student_assessment'),
        ),
        migrations.AddConstraint(
            model_name='assessmentclomapping',
            constraint=models.UniqueConstraint(fields=('assessment', 'clo'), name='unique_assessment_clo_mapping'),
        ),
    ]
