# Generated by Codex on 2026-03-15

from django.db import migrations, models
from django.db.models import Count, Max


def dedupe_clo_and_ga_mappings(apps, schema_editor):
    CLO = apps.get_model("obe", "CLO")
    CLOGAMapping = apps.get_model("obe", "CLOGAMapping")

    dup_clos = (
        CLO.objects.values("course_id", "clo_number")
        .annotate(cnt=Count("id"), max_id=Max("id"))
        .filter(cnt__gt=1)
    )
    for group in dup_clos:
        CLO.objects.filter(
            course_id=group["course_id"],
            clo_number=group["clo_number"],
        ).exclude(id=group["max_id"]).delete()

    dup_mappings = (
        CLOGAMapping.objects.values("clo_id", "ga_id")
        .annotate(cnt=Count("id"), max_id=Max("id"))
        .filter(cnt__gt=1)
    )
    for group in dup_mappings:
        CLOGAMapping.objects.filter(
            clo_id=group["clo_id"],
            ga_id=group["ga_id"],
        ).exclude(id=group["max_id"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("obe", "0005_assessment_studentassessment_assessmentclomapping_and_more"),
    ]

    operations = [
        migrations.RunPython(dedupe_clo_and_ga_mappings, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="clo",
            constraint=models.UniqueConstraint(
                fields=("course", "clo_number"),
                name="unique_clo_number_per_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="clogamapping",
            constraint=models.UniqueConstraint(
                fields=("clo", "ga"),
                name="unique_clo_ga_mapping",
            ),
        ),
    ]
