# Generated by Django 4.2 on 2026-03-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0005_clo_department_clo_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='bloom_level',
            field=models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='clo',
            constraint=models.UniqueConstraint(fields=('course', 'clo_number'), name='unique_clo_number_per_course'),
        ),
    ]
