# Generated by Codex on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obe", "0006_dedupe_and_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="OBEConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "clo_pass_threshold",
                    models.FloatField(default=60.0, help_text="Minimum percentage for CLO attainment"),
                ),
                (
                    "ga_pass_threshold",
                    models.FloatField(default=60.0, help_text="Minimum percentage for GA attainment"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OBE Configuration",
                "verbose_name_plural": "OBE Configuration",
            },
        ),
    ]
