# Generated by Django 4.2 on 2026-03-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0006_alter_clo_bloom_level_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clogamapping',
            constraint=models.UniqueConstraint(fields=('clo', 'ga'), name='unique_clo_ga_mapping'),
        ),
    ]
