# Generated by Django 5.2.5 on 2026-03-26 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0007_obeconfiguration'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessmentclomapping',
            name='weightage',
            field=models.FloatField(default=0, help_text='Weightage in percentage (0-100).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.CreateModel(
            name='StudentCLOPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_results', to='obe.assessment')),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='obe.clo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_performances', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'clo', 'assessment')},
            },
        ),
    ]
