# Generated by Django 4.2 on 2026-04-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0007_clogamapping_unique_clo_ga_mapping'),
        ('obe', '0007_obeconfiguration'),
    ]

    operations = [
    ]
