# Generated by Django 4.2 on 2026-07-01 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_batch_exit_survey_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_remove_student_is_active_remove_student_status'),
        ('obe', '0013_exit_survey_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniSurveyCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_window', models.CharField(choices=[('6_MONTHS', '6 Months Post Graduation'), ('1.5_YEARS', '1.5 Years Post Graduation'), ('3_YEARS', '3 Years Post Graduation')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_alumni_surveys', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_survey_cycles', to='core.batch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlumniSurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('is_locked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_survey_questions', to='obe.peo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GAReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direct_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('indirect_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_reports', to='core.batch')),
                ('ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='obe.ga')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ga', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='AlumniSurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='obe.alumnisurveycycle')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='obe.alumnisurveyquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_survey_responses', to='students.student')),
            ],
            options={
                'unique_together': {('cycle', 'student', 'question')},
            },
        ),
    ]
