# Generated by Django 4.2 on 2026-07-05

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0017_alter_clogamapping_clo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnisurveycycle',
            name='auto_extension_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumnisurveycycle',
            name='auto_extension_days',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='alumnisurveycycle',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnisurveycycle',
            name='response_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='alumnisurveycycle',
            name='survey_window',
            field=models.CharField(choices=[('6_MONTHS', '6 Months Post Graduation'), ('1.5_YEARS', '1.5 Years Post Graduation'), ('2_YEARS', '2 Years Post Graduation'), ('3_YEARS', '3 Years Post Graduation')], max_length=20),
        ),
    ]
