# Generated by Django 4.2 on 2026-07-06 16:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_batch_alumni_feedback_due_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obe', '0019_alumnisurveyresponse_current_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEOCQIRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attainment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kpi_threshold_at_trigger', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('remedial_plan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=30)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peo_cqi_records', to='core.batch')),
                ('peo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cqi_records', to='obe.peo')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_peo_cqis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('peo', 'batch')},
            },
        ),
        migrations.AddField(
            model_name='gapeomapping',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.CreateModel(
            name='PEOCQISubmissionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('root_cause_snapshot', models.TextField(blank=True, null=True)),
                ('remedial_plan_snapshot', models.TextField(blank=True, null=True)),
                ('status_at_time', models.CharField(max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('cqi_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='obe.peocqirecord')),
            ],
        ),
    ]
