# Generated by Django 4.2 on 2026-07-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0020_peocqirecord_gapeomapping_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gareport',
            name='breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gareport',
            name='course_feedback_coverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gareport',
            name='course_feedback_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gareport',
            name='coverage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gareport',
            name='exit_survey_coverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gareport',
            name='exit_survey_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gareport',
            name='formula_applied',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gareport',
            name='direct_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gareport',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
