# Generated by Django 4.2 on 2026-08-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0027_alter_clo_bloom_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='bloom_level',
            field=models.CharField(choices=[('C1', 'C1 - Remembering'), ('C2', 'C2 - Understanding'), ('C3', 'C3 - Applying'), ('C4', 'C4 - Analyzing'), ('C5', 'C5 - Evaluating'), ('C6', 'C6 - Creating')], default='C2', max_length=10),
        ),
    ]
