# Generated by Codex on 2026-08-07

import decimal
import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20260723_2346'),
        ('students', '0008_alter_student_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obe', '0029_alter_clo_bloom_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_type', models.CharField(choices=[('ALUMNI', 'Alumni Survey'), ('EMPLOYER', 'Employer Survey')], db_index=True, max_length=20)),
                ('question_text', models.TextField()),
                ('is_locked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('version_snapshot_id', models.UUIDField(blank=True, editable=False, help_text='Preserves original question IDs for historical response integrity', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_questions', to='obe.peo')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='core.program')),
            ],
            options={
                'ordering': ['survey_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PEOSurveyWeightConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alumni_weight', models.DecimalField(decimal_places=2, default=decimal.Decimal('50.00'), help_text='Percentage of the 20% indirect component from Alumni Survey (0-100)', max_digits=5)),
                ('employer_weight', models.DecimalField(decimal_places=2, default=decimal.Decimal('50.00'), help_text='Percentage of the 20% indirect component from Employer Survey (0-100)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peo_survey_weight_config', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniSurveySubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employment_status', models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-Employed / Entrepreneur'), ('HIGHER_STUDIES', 'Higher Studies'), ('UNEMPLOYED', 'Unemployed / Looking for job'), ('HOUSEWIFE', 'Housewife / Homemaker')], max_length=20, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='obe.alumnisurveycycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_survey_submissions', to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('cycle', 'student')},
            },
        ),
        migrations.CreateModel(
            name='EmployerSurveyCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_window', models.CharField(choices=[('6_MONTHS', '6 Months Post Graduation'), ('1.5_YEARS', '1.5 Years Post Graduation'), ('2_YEARS', '2 Years Post Graduation'), ('3_YEARS', '3 Years Post Graduation')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('response_threshold', models.DecimalField(decimal_places=2, default=decimal.Decimal('30.00'), max_digits=5)),
                ('auto_extension_days', models.PositiveIntegerField(default=2)),
                ('auto_extension_count', models.PositiveIntegerField(default=0)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_employer_surveys', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_survey_cycles', to='core.batch')),
                ('linked_alumni_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_survey_cycles', to='obe.alumnisurveycycle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerSurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_email', models.EmailField(db_index=True, max_length=255)),
                ('employer_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_name_at_org', models.CharField(blank=True, max_length=255, null=True)),
                ('response_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('token_sent_at', models.DateTimeField(blank=True, null=True)),
                ('token_used_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumni_student', models.ForeignKey(blank=True, help_text='The graduate this employer feedback is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_survey_about', to='students.student')),
                ('alumni_survey_submission', models.ForeignKey(blank=True, help_text='Links back to the alumni employment record that generated this survey', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_responses', to='obe.alumnisurveysubmission')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='obe.employersurveycycle')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'employer_email', 'alumni_student')},
            },
        ),
        migrations.CreateModel(
            name='AlumniSurveyAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumni_answers', to='obe.surveyquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='obe.alumnisurveysubmission')),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.CreateModel(
            name='EmployerSurveyAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employer_answers', to='obe.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='obe.employersurveyresponse')),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('response', 'question')},
            },
        ),
    ]
