# Generated by Django 4.2 on 2026-08-18 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_add_freeze_promotion_status'),
        ('obe', '0034_backfill_final_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_missions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='obe.mission')),
            ],
            options={
                'ordering': ['text'],
                'unique_together': {('mission', 'text')},
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visions', to='core.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisionKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='obe.vision')),
            ],
            options={
                'ordering': ['text'],
                'unique_together': {('vision', 'text')},
            },
        ),
        migrations.AlterField(
            model_name='clo',
            name='bloom_level',
            field=models.CharField(choices=[('C1', 'Remembering'), ('C2', 'Understanding'), ('C3', 'Applying'), ('C4', 'Analyzing'), ('C5', 'Evaluating'), ('C6', 'Creating')], default='C2', max_length=2),
        ),
        migrations.CreateModel(
            name='VisionMissionMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_mappings', to='obe.missionkeyword')),
                ('vision_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_mappings', to='obe.visionkeyword')),
            ],
            options={
                'unique_together': {('mission_keyword', 'vision_keyword')},
            },
        ),
        migrations.CreateModel(
            name='PEOKeywordMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peo_mappings', to='obe.missionkeyword')),
                ('peo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_mappings', to='obe.peo')),
                ('vision_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peo_mappings', to='obe.visionkeyword')),
            ],
            options={
                'unique_together': {('peo', 'mission_keyword', 'vision_keyword')},
            },
        ),
    ]
