# Generated by Django 6.0.7 on 2026-08-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0034_backfill_final_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='bloom_level',
            field=models.CharField(choices=[('C1', 'Remembering'), ('C2', 'Understanding'), ('C3', 'Applying'), ('C4', 'Analyzing'), ('C5', 'Evaluating'), ('C6', 'Creating')], default='C2', max_length=2),
        ),
    ]
