# Generated by Django 4.2 on 2026-08-20 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_add_freeze_promotion_status'),
        ('obe', '0036_visionmissioncqi'),
    ]

    operations = [
        migrations.AddField(
            model_name='gacqirecord',
            name='action_taken_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gacqirecord',
            name='implemented_in_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ga_cqi_closures', to='core.batch'),
        ),
        migrations.AddField(
            model_name='gacqirecord',
            name='resulting_attainment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='peocqirecord',
            name='action_taken_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peocqirecord',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peocqirecord',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_peo_cqis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peocqirecord',
            name='implemented_in_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peo_cqi_closures', to='core.batch'),
        ),
        migrations.AddField(
            model_name='peocqirecord',
            name='resulting_attainment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='peocqirecord',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED_IMPLEMENTED', 'Closed / Implemented'), ('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='VisionMissionCQIRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_type', models.CharField(choices=[('VISION', 'Vision'), ('MISSION', 'Mission')], max_length=10)),
                ('trigger_type', models.CharField(choices=[('SCHEDULED', 'Scheduled (3-5yr Review)'), ('MANUAL', 'Manual Review')], max_length=20)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_statement_snapshot', models.TextField()),
                ('decision', models.CharField(choices=[('RETAINED', 'Retained'), ('REVISED', 'Revised')], max_length=20)),
                ('justification', models.TextField()),
                ('new_statement', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REVIEWED', 'Reviewed')], default='REVIEWED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_mission_cqi_records', to='core.department')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vm_cqi_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date', '-created_at'],
            },
        ),
    ]
