# Generated by Django 4.2 on 2026-08-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0035_alter_clo_bloom_level'),
        ('obe', '0038_visionmissioncqi_closing_fields'),
    ]

    operations = [
    ]
