# Generated by Django 4.2 on 2026-08-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0039_merge_20260821_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clogamapping',
            name='clo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_mappings', to='obe.clo'),
        ),
        migrations.AlterUniqueTogether(
            name='clogamapping',
            unique_together={('clo', 'ga')},
        ),
    ]
