# Generated by Django 5.2.5 on 2026-06-24 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_curriculums', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obe_curriculum_versions', to='core.batch')),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='curriculum.curriculumversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_curriculums', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obe_curriculum_versions', to='core.program')),
            ],
            options={
                'verbose_name': 'Curriculum Version',
                'verbose_name_plural': 'Curriculum Versions',
                'ordering': ['-created_at'],
                'unique_together': {('program', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumVersionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='version_assignments', to='core.course')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_courses', to='curriculum.curriculumversion')),
            ],
            options={
                'verbose_name': 'Curriculum Version Course',
                'verbose_name_plural': 'Curriculum Version Courses',
                'ordering': ['semester_no', 'course__name'],
                'unique_together': {('version', 'course', 'semester_no')},
            },
        ),
    ]
