# Generated by Django 6.0.7 on 2026-08-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumversion',
            name='curriculum_mode',
            field=models.CharField(choices=[('progressive', 'Progressive'), ('complete', 'Complete')], default='progressive', max_length=20),
        ),
    ]
