# Generated by Django 4.2 on 2026-06-01 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_course_parent_course'),
        ('curriculum', '0002_alter_curriculumversion_batch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculumversion',
            unique_together={('program', 'version_no')},
        ),
        migrations.AlterField(
            model_name='curriculumversion',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obe_curriculum_versions', to='core.batch'),
        ),
    ]
