# Generated by Django 6.0.7 on 2026-08-19 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_course_custom_id'),
        ('curriculum', '0003_alter_curriculumversion_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Course Added'), ('removed', 'Course Removed'), ('updated', 'Course Updated'), ('semester_changed', 'Semester Changed')], max_length=50)),
                ('old_semester', models.IntegerField(blank=True, null=True)),
                ('new_semester', models.IntegerField(blank=True, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_history', to='core.course')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_history', to='curriculum.curriculumversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
