# Generated by Django 4.2 on 2026-06-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_batch_curriculum_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0003_alter_curriculumversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculumversion',
            unique_together={('program', 'version_no', 'batch')},
        ),
        migrations.AlterField(
            model_name='curriculumversion',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_curriculums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curriculumversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
