# Generated by Django 4.2 on 2026-06-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_batch_curriculum_version'),
        ('curriculum', '0004_alter_curriculumversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculumversion',
            unique_together={('program', 'version_no')},
        ),
    ]
