# Generated by Django 6.0.7 on 2026-08-14 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_freeze_promotion_status'),
        ('curriculum', '0002_curriculumversion_curriculum_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculumversion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumversioncourse',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(fields=('program', 'version_no'), name='unique_program_curriculum_version'),
        ),
        migrations.AddConstraint(
            model_name='curriculumversioncourse',
            constraint=models.UniqueConstraint(fields=('version', 'course', 'semester_no'), name='unique_version_course_semester'),
        ),
        migrations.RemoveField(
            model_name='curriculumversion',
            name='batch',
        ),
    ]
